publish build-state.svg directly to the Wiki
- deploy the badge via wiki, rather than a private gist

- fix printout for dnf-based distros
- automatically run kmod-compat-check once per week
- rename job to "get_distro_releases" (it's no longer debian/ubuntu specific)
- use "${badge}" variable for svg-file and pass it between steps
- add SHA to wiki-commit message

Co-authored-by: IOhannes m zmölnig <zmoelnig@umlautT.umlaeute.mur.at>

diff --git a/.github/workflows/kmod-compatibility-checks.yml b/.github/workflows/kmod-compatibility-checks.yml
--- a/.github/workflows/kmod-compatibility-checks.yml
+++ b/.github/workflows/kmod-compatibility-checks.yml
@@ -9,9 +9,11 @@ on:
     branches:
       - develop
       - main
+  schedule:
+    - cron: '37 5 * * 1'
 
 jobs:
-  get_debuntu_releases:
+  get_distro_releases:
     runs-on: ubuntu-latest
     steps:
       - name: install dependencies
@@ -54,9 +56,9 @@ jobs:
 
   kmod-compile:
     runs-on: ubuntu-latest
-    needs: get_debuntu_releases
+    needs: get_distro_releases
     strategy:
-      matrix: ${{ fromJson(needs.get_debuntu_releases.outputs.matrix) }}
+      matrix: ${{ fromJson(needs.get_distro_releases.outputs.matrix) }}
       fail-fast: false
     container: ${{ matrix.image }}
     env:
@@ -95,7 +97,7 @@ jobs:
           ${not_dnf5} || dnf5 upgrade -y --refresh
           ${not_dnf5} || dnf5 install -y --setopt=install_weak_deps=False --skip-unavailable lsb-release dkms kernel-devel kernel-headers kernel-modules-core
           not_dnf=true; if ${not_dnf5} && dnf --version>/dev/null; then not_dnf=false; fi
-          ${not_dnf5} || echo "running dnf5-based distribution (Fedora<41,...)"
+          ${not_dnf} || echo "running dnf-based distribution (Fedora<41,...)"
           ${not_dnf} || dnf upgrade -y --refresh
           ${not_dnf} || dnf install -y --setopt=install_weak_deps=False lsb-release dkms kernel-devel kernel-headers kernel-modules-core
 
@@ -193,29 +195,40 @@ jobs:
     needs: kmod-compile
     runs-on: ubuntu-latest
     steps:
-      - name: get status artifacts
+      - name: Checkout WIKI repository
+        uses: actions/checkout@v4
+        with:
+          repository: v4l2loopback/v4l2loopback.wiki.git
+          ref: master
+          token: ${{ secrets.PUSH2REPO_TOKEN }}
+      - name: Get status artifacts
         uses: actions/download-artifact@v4
-      - name: create badge
+      - name: Create badge
+        id: createbadge
         shell: bash
         run: |
+          badge=build-state.svg
+          echo "badge=${badge}" >> ${GITHUB_OUTPUT}
           find */ -type f -name "buildstate.txt" -exec grep -h . {} + | sort -uf > allstates.txt
           cat -n allstates.txt
           numtests=$(grep -c . allstates.txt)
-          echo -n > badge.svg
-          echo '<?xml version="1.0" encoding="UTF-8"?> <svg xmlns="http://www.w3.org/2000/svg" width="333" height="@height@">' | sed -e "s|@height@|$((numtests*22))|g">> badge.svg
-          echo '<style>.success {fill:#4C1} .skip {fill:#D3D3D3} .softfail {fill:#FE7D37} .failure {fill:#E05D44}</style> <g fill="#fff" text-anchor="left" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"> <linearGradient id="b" x2="0" y2="100%"> <stop offset="0" stop-color="#bbb" stop-opacity=".1"/> <stop offset="1" stop-opacity=".1"/> </linearGradient>' | sed -e "s|@height@|$((numtests * 22))|g" >> badge.svg
+          echo -n > "${badge}"
+          echo '<?xml version="1.0" encoding="UTF-8"?> <svg xmlns="http://www.w3.org/2000/svg" width="333" height="@height@">' | sed -e "s|@height@|$((numtests*22))|g">> "${badge}"
+          echo '<style>.success {fill:#4C1} .skip {fill:#D3D3D3} .softfail {fill:#FE7D37} .failure {fill:#E05D44}</style> <g fill="#fff" text-anchor="left" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"> <linearGradient id="b" x2="0" y2="100%"> <stop offset="0" stop-color="#bbb" stop-opacity=".1"/> <stop offset="1" stop-opacity=".1"/> </linearGradient>' | sed -e "s|@height@|$((numtests * 22))|g" >> "${badge}"
           cat -n allstates.txt | while read num os _ version kernel state; do
             dy=$(((num-1)*22))
-            echo "ENTRY ${num} ${os} ${version} :: ${kernel} @ $dy" >&2
             echo '<g transform="translate(0 @dy@)" mask="url(#anybadge_1)"> <path fill="#555" d="M0 0h148v20H0z"/> <path class="@state@" d="M148 0h185v20H148z"/> <path fill="url(#b)" d="M0 0h333v20H0z"/> <text x="9.0" y="15" fill="#010101" fill-opacity=".3">@os@/@version@</text> <text x="8.0" y="14">@os@/@version@</text> <text x="156.5" y="15" fill="#010101" fill-opacity=".3">@kernel@</text> <text x="155.5" y="14">@kernel@</text> </g>' | sed -e "s|@dy@|${dy}|g" -e "s|@state@|${state}|g" -e "s|@os@|${os}|g" -e "s|@version@|${version}|g" -e "s|@kernel@|${kernel}|g"
-          done >> badge.svg
-          echo '</g> </svg>' >> badge.svg
-          cat badge.svg
-      - name: deploy badge
-        uses: exuanbo/actions-deploy-gist@v1
-        with:
-          token: ${{ secrets.GIST_SECRET }}
-          gist_id: f877d3367ab47ffd2d203b1062c41825
-          file_path: badge.svg
-          file_type: text
+          done >> "${badge}"
+          echo '</g> </svg>' >> "${badge}"
+          cat "${badge}"
+      - name: Deploy badge to wiki
         if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
+        env:
+          badge: ${{ steps.createbadge.outputs.badge }}
+        run: |
+          echo "${badge}"
+          git config user.name "github-actions[bot]"
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git add "${badge}"
+          git commit -m "Update build-state.svg for ${{ github.sha }}"
+          git push
