Create a badge with all kernels tested in the CI
whenever a CI runs on `main`, this updates a mega-badge with status for all kernels that were tested.

Co-authored-by: IOhannes m zmölnig <zmoelnig@umlautT.umlaeute.mur.at>

diff --git a/.github/workflows/kmod-compatibility-checks.yml b/.github/workflows/kmod-compatibility-checks.yml
--- a/.github/workflows/kmod-compatibility-checks.yml
+++ b/.github/workflows/kmod-compatibility-checks.yml
@@ -52,7 +52,7 @@ jobs:
           apt-get update --quiet;
           apt-get install --yes --no-install-recommends kmod
           apt-get install --yes --no-install-recommends dkms || true
-          apt-get install --yes --no-install-recommends dctrl-tools || true
+          apt-get install --yes --no-install-recommends lsb-release dctrl-tools || true
           apt-get install --yes --no-install-recommends linux-headers-generic linux-headers || true
           grep-aptavail -n -s Package  -F Provides -X linux-headers -o -F Provides -X linux-headers-generic \
                 | xargs apt-get install --yes --no-install-recommends || true
@@ -90,11 +90,60 @@ jobs:
             fi;
             make KERNELRELEASE="${kver}" clean || test ${ret} -ne 0
           done
+          statefile=buildstate.txt
+          osname="$(lsb_release -si)"
+          osversion="$(lsb_release -sr)"
+          osrelease="$(lsb_release -sc)"
+          rm -rf "${statefile}"
+          for k in ${succeeded}; do
+            echo "${osname} ${osversion} ${osrelease} ${k} success"
+          done >> "${statefile}"
+          for k in ${skipped}; do
+            echo "${osname} ${osversion} ${osrelease} ${k} skip"
+          done >> "${statefile}"
+          for k in ${failed}; do
+            echo "${osname} ${osrelease} ${k} failure"
+          done >> "${statefile}"
+          echo "#### Successful builds for kernels: ${succeeded}";
+          if [ "x${skipped}" != "x" ]; then
+            echo "#### Skipped kernels: ${skipped}";
+          fi
           if [ "x${failed}" != "x" ]; then
             echo "#### Failed kernels: ${failed}";
             exit 1
           fi
-          if [ "x${skipped}" != "x" ]; then
-            echo "#### Skipped kernels: ${skipped}";
-          fi
-          echo "#### Successful builds for kernels: ${succeeded}";
+      - name: Publish state
+        if: success() || failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.series }}
+          path: buildstate.txt
+
+  make_badges:
+    if: always()
+    needs: kmod-compile
+    runs-on: ubuntu-latest
+    steps:
+      - name: get status artifacts
+        uses: actions/download-artifact@v4
+      - name: create badge
+        shell: bash
+        run: |
+          find */ -type f -name "buildstate.txt" -exec grep -h . {} + | sort -u > allstates.txt
+          numtests=$(grep -c . allstates.txt)
+          echo -n > badge.svg
+          echo '<?xml version="1.0" encoding="UTF-8"?> <svg xmlns="http://www.w3.org/2000/svg" width="333" height="@height@">' | sed -e "s|@height@|$((numtests*22))|g">> badge.svg
+          echo '<style>.success {fill:#4C1} .skip {fill:#D3D3D3} .failure {fill:#E05D44}</style> <g fill="#fff" text-anchor="left" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11"> <linearGradient id="b" x2="0" y2="100%"> <stop offset="0" stop-color="#bbb" stop-opacity=".1"/> <stop offset="1" stop-opacity=".1"/> </linearGradient>' | sed -e "s|@height@|$((numtests * 22))|g" >> badge.svg
+          cat -n allstates.txt | while read num os _ version kernel state; do
+            echo '<g transform="translate(0 @dy@)" mask="url(#anybadge_1)"> <path fill="#555" d="M0 0h148v20H0z"/> <path class="@state@" d="M148 0h185v20H148z"/> <path fill="url(#b)" d="M0 0h333v20H0z"/> <text x="9.0" y="15" fill="#010101" fill-opacity=".3">@os@/@version@</text> <text x="8.0" y="14">@os@/@version@</text> <text x="156.5" y="15" fill="#010101" fill-opacity=".3">@kernel@</text> <text x="155.5" y="14">@kernel@</text> </g>' | sed -e "s|@dy@|$((22*(num-1)))|g" -e "s|@state@|${state}|g" -e "s|@os@|${os}|g" -e "s|@version@|${version}|g" -e "s|@kernel@|${kernel}|g"
+          done >> badge.svg
+          echo '</g> </svg>' >> badge.svg
+          cat badge.svg
+      - name: deploy badge
+        uses: exuanbo/actions-deploy-gist@v1
+        with:
+          token: ${{ secrets.GIST_SECRET }}
+          gist_id: f877d3367ab47ffd2d203b1062c41825
+          file_path: badge.svg
+          file_type: text
+        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
